import img1 from "../assets/img/1.jpeg";
import img2 from "../assets/img/2.jpeg";
import img3 from "../assets/img/3.jpeg";
import img4 from "../assets/img/4.jpeg";
import img5 from "../assets/img/5.jpeg";
import img6 from "../assets/img/6.jpeg";

export default [
  {
    id: 1,
    available: 0,
    img: img1,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes ",
    pricing: 200,
  },
  {
    id: 2,
    available: 1,
    img: img2,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 3,
    available: 0,
    img: img3,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 4,
    available: 2,
    img: img4,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 5,
    available: 1,
    img: img5,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 6,
    available: 1,
    img: img6,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },

  {
    id: 7,
    available: 1,
    img: img1,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 8,
    available: 1,
    img: img2,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 9,
    available: 1,
    img: img3,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
  {
    id: 10,
    available: 1,
    img: img4,
    rating: "6.2",
    reviewCount: 4,
    country: "usa",
    title: "life lessons with katie zaferes",
    pricing: 200,
  },
];
